version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    working_dir: /app
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_ENGINE: mariadb
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: test
      DB_LOGGING: true
      DB_SYNC: true
    networks:
      - custom_network
    ports:
      - "4001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
      until nc -z mysql 3306; do
        echo 'Esperando a MySQL...';
        sleep 3;
      done;
      node ./dist/index.js"
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    networks:
      - custom_network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  custom_network:
    driver: bridge
