version: '3'

services:
  api:
    working_dir: /app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_ENGINE=${DB_ENGINE}
      - DB_LOGGING=${DB_LOGGING}
      - DB_SYNC=${DB_SYNC}
    network_mode: bridge
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev